# Autogenerated 2025-10-15 22:14:07

terraform {
  backend "azurerm" {
    resource_group_name  = "rg-terraform-state"
    storage_account_name = "sgtoolboxtf"
    container_name       = "tfstate"
  }
}