while read -r path; do
  mkdir -p "$(dirname "terraform/$path")"

  # Hoppa över kataloger (de slutar med "/")
  if [[ "$path" != */ ]]; then
    file="terraform/$path"
    # Skapa fil och skriv header om den är tom
    if [[ ! -s "$file" ]]; then
      echo "# Autogenerated $(date '+%Y-%m-%d %H:%M:%S')" > "$file"
      echo "Created $file"
    else
      echo "Skipped $file (already exists)"
    fi
  fi
done < lista.txt
