# Autogenerated 2025-10-15 22:14:07
# Block 1: Terraform version
terraform {
  required_version = ">= 1.6.0"
  
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

# Block 2: Azure Provider
provider "azurerm" {
  features {}
  
  subscription_id = var.subscription_id
}