# Autogenerated 2025-10-15 22:14:07
#output "resource_group_name" {
#  description = "Name of the resource group"
#  value       = azurerm_resource_group.main.name
#}

output "location" {
  description = "Azure region"
  value       = var.location
}