# Autogenerated 2025-10-15 22:14:07

# Setting Azure region variable
variable "location" {
  description = "Azure region"
  type        = string
  default     = "swedencentral"
}


variable "environment" {
  description = "Environment (qa/prod)"
  type        = string
  default     = "qa"
}


#variable "postgres_admin_password" {
#  description = "PostgreSQL administrator password"
#  type        = string
#  sensitive   = true
#}

#
#variable "openai_api_key" {
#  description = "OpenAI API key"
#  type        = string
#  sensitive   = true
#}


#variable "flask_secret_key" {
#  description = "Flask secret key for sessions"
#  type        = string
#  sensitive   = true
#}

#variable "admin_password" {
#  description = "Admin user password"
#  type        = string
#  sensitive   = true
#}