# Autogenerated 2025-10-15 22:14:07
variable "location" {
  description = "Azure region"
  type        = string
  default     = "swedencentral"
}

variable "environment" {
  description = "Environment (qa/prod)"
  type        = string
  default     = "qa"
}