services:
  web:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile
    image: summary_automation:${TAG:-dev}
    container_name: summary_automation

    # Låt Compose ladda variabler från .env i repo-roten
    env_file:
      - ../.env

    # Mounta själva .env in i containern om din kod kör load_dotenv()
    volumes:
      - ../.env:/app/.env:ro
      - ../input:/app/input
      - ../reference:/app/reference
      - ../static/logo:/app/static/logo
      - ../static/backgrounds:/app/static/backgrounds

    ports:
      - "${HOST_PORT:-8000}:8000"
    restart: unless-stopped
