services:
  web:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile
    image: sg_toolbox:${TAG:-dev}
    container_name: sg_toolbox

    # Låt Compose ladda variabler från .env i repo-roten
    env_file:
      - ../.env

    # Mounta själva .env in i containern om din kod kör load_dotenv()
    volumes:
      - ../.env:/app/.env:ro
      - ../data/input:/app/input
      - ../data/reference:/app/reference
      - ../ui/static/logo:/app/static/logo
      - ../ui/static/backgrounds:/app/static/backgrounds

    ports:
      - "${HOST_PORT:-8000}:8000"
    restart: unless-stopped
